<style>
container {
	width: 100%;
	white-space: nowrap;
}

div.popup-container {
	position: fixed;
	top: 0;
	left: 0;
	width: 100%;
	height: 100%;
	background-color: rgba(0, 0, 0, 0.2);
	display: flex;
	flex-direction: row;
	align-items: center;
	justify-content: center;
}

div.popup-container div.popup {
	background-color: #f0f0f0;
	width: 350px;
	border-radius: 5px;
	padding: 20px 25px 30px 25px;
}

div.popup-container div.popup h2 {
	display: flex;
	flex-direction: row;
	align-items: center;
	justify-content: space-between;
	margin-bottom: 30px;
	color: #30475e;
}
</style>
<div class="popup-container" id="login-popup">
	<div class="popup">
		<h2>
			<span>Bejelentkezés</span>
		</h2>
		<form action="/login" method="POST">
		<?php if (isset($_SESSION['checkPassword'])) { ?>
		<?php if ($_SESSION['checkPassword'] === 'invalidData') : ?>
			<div class="alert alert-danger">
                                Sikertelen bejelentkezés!
           </div>
       	<?php endif ?>
       	<?php if ($_SESSION['checkPassword'] === 'accountIsNotActive') : ?>
			<div class="alert alert-danger">
                                Nem aktív a felhasználó!
           </div>
       	<?php endif ?>
       	<?php  } ?>
			<div class="input-group">
				<input type="text" placeholder="Felhasználó név" name="username"
					class="form-control" value="<?php if (isset($_SESSION['username'])) { echo $_SESSION['username']; }?>">
			</div>
			<br>
			<div class="input-group">
				<input type="password" placeholder="Jelszó" name="pw"
					class="form-control">
			</div>
			<br>
			<button type="submit" name="sendButton" class="btn btn-info">Bejelentkezés</button>
		</form>
	</div>
</div>