<?php
header('Content-Type: text/html; charset=iso-8859-2');
require_once 'passwordchange.phtml';
$menus = [
    'Ellátás',
    'NFA',
    'GINOP',
    'TOP',
    'Ügyfél törzs',
    'Munkáltatói törzs'
];
$NFAsubmenus = [
    'EHT',
    'NYDM'
];
?>
<!--  fõmenü -->
<nav class="navbar navbar-expand-xxl bg-light">
	<div class="container-fluid">
		<a class="navbar-brand" style="cursor: default;">Fõmenü</a>
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse"
			data-bs-target="#navbarSupportedContent"
			aria-controls="navbarSupportedContent" aria-expanded="false"
			aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav me-auto mb-2 mb-lg-2">
    <?php
    foreach ($menus as $menu) {
        if ($menu == $menus[1]) {
            ?>
				<li class="nav-item dropdown"><a class="nav-link dropdown-toggle"
					href="#" role="button" data-bs-toggle="dropdown"
					aria-expanded="false">
                		<?= $menu;?>
              		</a>
					<ul class="dropdown-menu">
                		<?php foreach($NFAsubmenus as $NFAsubmenu){ ?>
                	<li class="nav-item"><a class="dropdown-item" href="#"><?= $NFAsubmenu; ?></a>
						</li>
                	<?php } ?>
               		</ul></li>
				<li class="nav-item dropdown"></li>
                 	<?php } elseif ($menu == $menus[0]) { ?>
				<li class="nav-item dropdown"><a class="nav-link dropdown-toggle"
					href="#" role="button" data-bs-toggle="dropdown"
					aria-expanded="false">
                		<?= $menu;?>
                	</a>
					<ul class="dropdown-menu">
						<li class="nav-item"><a class="dropdown-item" href="#">A</a></li>
						<li class="nav-item"><a class="dropdown-item" href="#">B</a></li>
						<li class="nav-item"><a class="dropdown-item" href="#">C</a></li>
					</ul></li>
              	<?php } elseif ($menu == $menus[2]) { ?>
              	<li class="nav-item dropdown"><a
					class="nav-link dropdown-toggle" href="#" role="button"
					data-bs-toggle="dropdown" aria-expanded="false">
                		<?= $menu;?>
                	</a>
					<ul class="dropdown-menu">
						<li class="nav-item"><a class="dropdown-item" href="#">A</a></li>
						<li class="nav-item"><a class="dropdown-item" href="#">B</a></li>
						<li class="nav-item"><a class="dropdown-item" href="#">C</a></li>
					</ul></li>
              	<?php } elseif ($menu == $menus[3]) { ?>
              	<li class="nav-item dropdown"><a
					class="nav-link dropdown-toggle" href="#" role="button"
					data-bs-toggle="dropdown" aria-expanded="false">
                		<?= $menu;?>
                	</a>
					<ul class="dropdown-menu">
						<li class="nav-item"><a class="dropdown-item" href="#">A</a></li>
						<li class="nav-item"><a class="dropdown-item" href="#">B</a></li>
						<li class="nav-item"><a class="dropdown-item" href="#">C</a></li>
					</ul></li>
              	<?php } elseif ($menu == $menus[4]) { ?>
              	<li class="nav-item dropdown"><a
					class="nav-link dropdown-toggle" href="#" role="button"
					data-bs-toggle="dropdown" aria-expanded="false">
                		<?= $menu;?>
                	</a>
					<ul class="dropdown-menu">
						<li class="nav-item"><a class="dropdown-item" href="client.php">Új
								Ügyfél</a></li>
						<li class="nav-item"><a class="dropdown-item" href="#">Ügyfél
								adatok karbantartása</a></li>
					</ul></li>
              	<?php } elseif ($menu == $menus[5]) { ?>
              	<li class="nav-item dropdown"><a
					class="nav-link dropdown-toggle" href="#" role="button"
					data-bs-toggle="dropdown" aria-expanded="false">
                		<?= $menu;?>
                	</a>
					<ul class="dropdown-menu">
						<li class="nav-item"><a class="dropdown-item"
							href="newemployer.php">Új munkáltató</a></li>
						<li class="nav-item"><a class="dropdown-item" href="#">Munkáltatói
								adatok karbantartása</a></li>
					</ul></li>
						<?php
        }
        ?>
                 	<?php } ?>
                <li class="nav-item"><a href=""
					class=" btn rounded-3 add-new-client-btn" id=""
					data-bs-toggle="modal" data-bs-target="#changepassword">Jelszó
						módosítása</a></li>
			</ul>
		</div>
	</div>
	<!--  admin menü -->
	<?php if($_SESSION['accounttype'] === "Rendszergazda"): ?>
	<nav class="navbar navbar-expand-xl bg-light"
		style="brand-hover-color: #214263">
		<div class="container">
			<a class="navbar-brand">Admin menü</a>
			<button class="navbar-toggler" type="button"
				data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent1"
				aria-controls="navbarSupportedContent" aria-expanded="false"
				aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarSupportedContent1">
				<ul class="navbar-nav me-auto mb-2 mb-lg-0">
					<li class="nav-item"><a class="nav-link active" aria-current="page"
						href="register.php">Új felhasználnó hozzáadása</a></li>
					<li class="nav-item"><a class="nav-link active" aria-current="page"
						href="update.php">Felhasználok adatmódosítása</a></li>
				</ul>
			</div>
		</div>
	</nav>
</nav>
<?php else: ?>
</nav>
<?php

endif;

var_dump($_COOKIE);
var_dump($_SESSION['accounttype']);
?>
