<?php 
header('Content-Type: text/html; charset=iso-8859-2');
$menus = [
    'Ellátás',
    'NFA',
    'GINOP',
    'TOP',
    'Ügyfél törzs',
    'Munkáltatói törzs'
];
$NFAsubmenus = [
    'EHT',
    'NYDM'
]; 

if($params['tipus'] === "Felhasználó"): 
?>
<nav class="navbar navbar-expand-md"
	style="brand-hover-color: #214263; background-color: #214263;">
	<div class="container-fluid">
		<a class="navbar-brand" href="/" disabled="disabled">Fõmenü</a>
		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav me-auto mb-2 mb-lg-0">
    <?php
    
    foreach ($menus as $menu) {
        if ($menu == $menus[1]) {
            ?>
				<li class="nav-item dropdown"><a class="nav-link dropdown-toggle"
					href="#" role="button" data-bs-toggle="dropdown"
					aria-expanded="false">
                		<?= $menu;?>
              		</a>
					<ul class="dropdown-menu">
                		<?php foreach($NFAsubmenus as $NFAsubmenu){ ?>
                	<li class="nav-item"><a class="dropdown-item" href="#"><?= $NFAsubmenu; ?></a>
						</li>
                	<?php } ?>
               		</ul></li>
				<li class="nav-item dropdown"></li>
                 	<?php } elseif ($menu == $menus[0]) { ?>
				<li class="nav-item dropdown"><a class="nav-link dropdown-toggle"
					href="#" role="button" data-bs-toggle="dropdown"
					aria-expanded="false">
                		<?= $menu;?>
                	</a>
					<ul class="dropdown-menu">
						<li class="nav-item"><a class="dropdown-item" href="#">A</a></li>
						<li class="nav-item"><a class="dropdown-item" href="#">B</a></li>
						<li class="nav-item"><a class="dropdown-item" href="#">C</a></li>
					</ul></li>
              	<?php } elseif ($menu == $menus[2]) { ?>
              	<li class="nav-item dropdown"><a
					class="nav-link dropdown-toggle" href="#" role="button"
					data-bs-toggle="dropdown" aria-expanded="false">
                		<?= $menu;?>
                	</a>
					<ul class="dropdown-menu">
						<li class="nav-item"><a class="dropdown-item" href="#">A</a></li>
						<li class="nav-item"><a class="dropdown-item" href="#">B</a></li>
						<li class="nav-item"><a class="dropdown-item" href="#">C</a></li>
					</ul></li>
              	<?php } elseif ($menu == $menus[3]) { ?>
              	<li class="nav-item dropdown"><a
					class="nav-link dropdown-toggle" href="#" role="button"
					data-bs-toggle="dropdown" aria-expanded="false">
                		<?= $menu;?>
                	</a>
					<ul class="dropdown-menu">
						<li class="nav-item"><a class="dropdown-item" href="#">A</a></li>
						<li class="nav-item"><a class="dropdown-item" href="#">B</a></li>
						<li class="nav-item"><a class="dropdown-item" href="#">C</a></li>
					</ul></li>
              	<?php } elseif ($menu == $menus[4]) { ?>
              	<li class="nav-item dropdown"><a
					class="nav-link dropdown-toggle" href="#" role="button"
					data-bs-toggle="dropdown" aria-expanded="false">
                		<?= $menu;?>
                	</a>
					<ul class="dropdown-menu">
						<li class="nav-item"><a class="dropdown-item" href="client.php">Új
								Ügyfél</a></li>
						<li class="nav-item"><a class="dropdown-item" href="#">Ügyfél
								adatok karbantartása</a></li>
					</ul></li>
              	<?php } elseif ($menu == $menus[5]) { ?>
              	<li class="nav-item dropdown"><a
					class="nav-link dropdown-toggle" href="#" role="button"
					data-bs-toggle="dropdown" aria-expanded="false">
                		<?= $menu;?>
                	</a>
					<ul class="dropdown-menu">
						<li class="nav-item"><a class="dropdown-item"
							href="newemployer.php">Új munkáltató</a></li>
						<li class="nav-item"><a class="dropdown-item" href="#">Munkáltatói
								adatok karbantartása</a></li>
					</ul></li>
						<?php
            }
            ?>
                 	<?php } ?>
                <li class="nav-item"><a class="nav-link"
					href="changepassword.php">Jelszó módosítás</a></li>

			</ul>
		</div>
	</div>
</nav>
<?php else: ?>
<nav class="navbar navbar-expand-lg bg-light"
	style="brand-hover-color: #214263">
	<div class="container-fluid">
		<a class="navbar-brand">Fõmenü</a>
		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav me-auto mb-2 mb-lg-0">
                	<?php

foreach ($menus as $menu) {
            if ($menu == $menus[1]) {
                ?>
				<li class="nav-item dropdown"><a class="nav-link dropdown-toggle"
					href="#" role="button" data-bs-toggle="dropdown"
					aria-expanded="false">
                		<?= $menu;?>
              		</a>
					<ul class="dropdown-menu">
                		<?php foreach($NFAsubmenus as $NFAsubmenu){ ?>
                	<li class="nav-item"><a class="dropdown-item" href="#"><?= $NFAsubmenu; ?></a>
						</li>
                	<?php } ?>
               		</ul></li>
				<li class="nav-item dropdown"></li>
                 	<?php } elseif ($menu == $menus[0]) { ?>
				<li class="nav-item dropdown"><a class="nav-link dropdown-toggle"
					href="#" role="button" data-bs-toggle="dropdown"
					aria-expanded="false">
                		<?= $menu;?>
                	</a>
					<ul class="dropdown-menu">
						<li class="nav-item"><a class="dropdown-item" href="#">A</a></li>
						<li class="nav-item"><a class="dropdown-item" href="#">B</a></li>
						<li class="nav-item"><a class="dropdown-item" href="#">C</a></li>
					</ul></li>
              	<?php } elseif ($menu == $menus[2]) { ?>
              	<li class="nav-item dropdown"><a
					class="nav-link dropdown-toggle" href="#" role="button"
					data-bs-toggle="dropdown" aria-expanded="false">
                		<?= $menu;?>
                	</a>
					<ul class="dropdown-menu">
						<li class="nav-item"><a class="dropdown-item" href="#">A</a></li>
						<li class="nav-item"><a class="dropdown-item" href="#">B</a></li>
						<li class="nav-item"><a class="dropdown-item" href="#">C</a></li>
					</ul></li>
              	<?php } elseif ($menu == $menus[3]) { ?>
              	<li class="nav-item dropdown"><a
					class="nav-link dropdown-toggle" href="#" role="button"
					data-bs-toggle="dropdown" aria-expanded="false">
                		<?= $menu;?>
                	</a>
					<ul class="dropdown-menu">
						<li class="nav-item"><a class="dropdown-item" href="#">A</a></li>
						<li class="nav-item"><a class="dropdown-item" href="#">B</a></li>
						<li class="nav-item"><a class="dropdown-item" href="#">C</a></li>
					</ul></li>
              	<?php } elseif ($menu == $menus[4]) { ?>
              	<li class="nav-item dropdown"><a
					class="nav-link dropdown-toggle" href="#" role="button"
					data-bs-toggle="dropdown" aria-expanded="false">
                		<?= $menu;?>
                	</a>
					<ul class="dropdown-menu">
						<li class="nav-item"><a class="dropdown-item" href="client.php">Új ügyféll</a></li>
						<li class="nav-item"><a class="dropdown-item" href="#">Ügyfél
								adatok karbantartása</a></li>
					</ul></li>
              	<?php } elseif ($menu == $menus[5]) { ?>
              	<li class="nav-item dropdown"><a
					class="nav-link dropdown-toggle" href="#" role="button"
					data-bs-toggle="dropdown" aria-expanded="false">
                		<?= $menu;?>
                	</a>
					<ul class="dropdown-menu">
						<li class="nav-item"><a class="dropdown-item"
							href="newemployer.php">új munkáltató</a></li>
						<li class="nav-item"><a class="dropdown-item" href="#">Munkáltatói
								adatok karbantartása</a></li>
					</ul></li>
						<?php
            }
            ?>
                 	<?php } ?>
                    <li class="nav-item"><a class="nav-link"
					href="changepassword.php">Jelszó módosítás</a></li>
			</ul>
		</div>
	</div>
	<nav class="navbar navbar-expand-lg bg-light"
		style="brand-hover-color: #214263">
		<div class="container-fluid">
			<a class="navbar-brand">Admin menü</a>
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav me-auto mb-2 mb-lg-0">
					<li class="nav-item"><a class="nav-link active" aria-current="page"
						href="register.php">Új felhasználnó hozzáadása</a></li>
					<li class="nav-item"><a class="nav-link active" aria-current="page"
						href="update.php">Felhasználok adatmódosítása</a></li>
				</ul>
			</div>
		</div>
	</nav>
</nav>
<?php endif; ?> 
<?php 
var_dump($_COOKIE) ;
var_dump($_SESSION) ;
?>
