<!DOCTYPE html>
<html lang="hu">
<head>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>KIR</title>
<link rel="stylesheet"
	href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.3/css/bootstrap.min.css"
	integrity="sha512-SbiR/eusphKoMVVXysTKG/7VseWii+Y3FdHrt0EpKgpToZeemhqHeZeLWLhJutz/2ut2Vw1uQEj2MbRF+TVBUA=="
	crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet"
	href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<link rel="stylesheet"
	href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.2/themes/base/jquery-ui.min.css"
	integrity="sha512-ELV+xyi8IhEApPS/pSj66+Jiw+sOT1Mqkzlh8ExXihe4zfqbWkxPRi8wptXIO9g73FSlhmquFlUOuMSoXz5IRw=="
	crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet"
	href="https://code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">

<script type="text/javascript" src="../public/function.js"></script>
<script
	src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.js"
	integrity="sha512-8Z5++K1rB3U+USaLKG6oO8uWWBhdYsM3hmdirnOEWp8h2B1aOikj5zBzlXs8QOrvY9OxEnD2QDkbSKKpfqcIWw=="
	crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script
	src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
	integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
	crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.6.0.js"></script>
<script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>

<script
	src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.3/js/bootstrap.min.js"
	integrity="sha512-1/RvZTcCDEUjY/CypiMz+iqqtaoQfAITmNSJY17Myp4Ms5mdxPS5UV7iOfdZoxcGhzFbOm6sntTKJppjvuhg4g=="
	crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script
	src="https://cdnjs.cloudflare.com/ajax/libs/jquery.inputmask/5.0.8/jquery.inputmask.min.js"
	integrity="sha512-efAcjYoYT0sXxQRtxGY37CKYmqsFVOIwMApaEbrxJr4RwqVVGw8o+Lfh/+59TU07+suZn1BWq4fDl5fdgyCNkw=="
	crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<!-- <script src='../public/datepicker-hu.js' type='text/javascript'></script>-->
<link rel="stylesheet" type="text/css" href="public/style.css">
<script type="text/javascript" src="public/function.js"></script>
</head>
<body>
	<div class="row" style="background-color: #214263;">
		<div class="col-md-3">
			<img src="../public/logo.jpeg" width=160px height=160px>
		</div>
		<div class="col-md-6">
			<h1>
				<center style="color: #ffffff">
					SZABOLCS-SZATMÁR-BEREG VÁRMEGYEI <br> KORMÁNYHIVATAL <br> Központi
					Irányító Rendszere
				</center>
			</h1>
		</div>
		<div class="col-md-3 px-5 py-5" style="text-align: right;">
			<?php if($params['bejelentkezve']): ?>
			<form action="logout" method="POST">
				<button type="submit" class="btn btn-sm btn-danger m-2">
					Kijelentkezés <i class="bi bi-box-arrow-left"></i>
				</button>
			</form>
			<?php else : ?>
			<form action="logout" method="POST">
				<button type="submit" class="btn btn-sm btn-success m-2">
					Bejelentkezés <i class="bi bi-box-arrow-left"></i>
				</button>
			</form>
			<?php endif; ?> 
		</div>
	</div>
	<main>
		<div class="container">
		 <?= $params['content'] ?>
		 </div>
	</main>
</body>

</html>